name: Running linters

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run Ruff
        run: ruff check . --config=ruff.toml
